### ISSUE TITLE
Why did my pull request fail the checks?

### ISSUE THREAD

**Issue by tclune** [nasa/Open-Source-Catalog#61]
Pull request #60 failed the checks, but the log does not tell me anything.

The nature of the changes was quite small, and I do not see anything amiss by eye:

$ npm test
> open-source-catalog@1.0.0 pretest /home/travis/build/nasa/Open-Source-Catalog
> npm run lint
> open-source-catalog@1.0.0 lint /home/travis/build/nasa/Open-Source-Catalog
> eslint . --ext .json --ext .md
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'concat-stream'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/nasa/Open-Source-Catalog/node_modules/eslint/bin/eslint.js:30:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by JustinGOSSES** [comment]
looks like this was merged before
